<?php
// ─── AI Courses Data ──────────────────────────────────────────────────────────

$courses = [
    [
        'id'          => 1,
        'slug'        => 'machine-learning-fundamentals',
        'title'       => 'Machine Learning Fundamentals',
        'subtitle'    => 'Master the core concepts powering modern AI',
        'category'    => 'Machine Learning',
        'level'       => 'Beginner',
        'duration'    => '12 weeks',
        'lessons'     => 48,
        'students'    => 24800,
        'rating'      => 4.9,
        'reviews'     => 3210,
        'price'       => 149,
        'old_price'   => 299,
        'instructor'  => 'Dr. Sarah Chen',
        'instructor_title' => 'AI Research Scientist, MIT',
        'color'       => '#7c3aed',
        'icon'        => 'brain',
        'badge'       => 'Bestseller',
        'tags'        => ['Python', 'Scikit-learn', 'NumPy', 'Pandas'],
        'description' => 'Begin your AI journey with a comprehensive foundation in machine learning. From linear regression to ensemble methods, this course covers everything you need to build real-world ML systems.',
        'outcomes'    => [
            'Understand supervised and unsupervised learning',
            'Build and evaluate ML models from scratch',
            'Apply regularization and optimization techniques',
            'Deploy models to production environments',
        ],
        'curriculum'  => [
            ['title' => 'Introduction to ML', 'lessons' => 6],
            ['title' => 'Supervised Learning', 'lessons' => 10],
            ['title' => 'Unsupervised Learning', 'lessons' => 8],
            ['title' => 'Model Evaluation & Tuning', 'lessons' => 8],
            ['title' => 'Advanced Algorithms', 'lessons' => 10],
            ['title' => 'Real-World Projects', 'lessons' => 6],
        ],
    ],
    [
        'id'          => 2,
        'slug'        => 'deep-learning-neural-networks',
        'title'       => 'Deep Learning & Neural Networks',
        'subtitle'    => 'Build cutting-edge neural architectures',
        'category'    => 'Deep Learning',
        'level'       => 'Intermediate',
        'duration'    => '16 weeks',
        'lessons'     => 64,
        'students'    => 18500,
        'rating'      => 4.8,
        'reviews'     => 2890,
        'price'       => 199,
        'old_price'   => 399,
        'instructor'  => 'Prof. Alex Kumar',
        'instructor_title' => 'Deep Learning Lead, Google Brain',
        'color'       => '#0ea5e9',
        'icon'        => 'network',
        'badge'       => 'Top Rated',
        'tags'        => ['PyTorch', 'TensorFlow', 'CNNs', 'RNNs'],
        'description' => 'Dive deep into neural network architectures. Master CNNs, RNNs, Transformers, and GANs while building projects that push the boundaries of what AI can do.',
        'outcomes'    => [
            'Design deep neural network architectures',
            'Train models on GPU with PyTorch & TensorFlow',
            'Implement CNNs for computer vision tasks',
            'Build sequence models for NLP applications',
        ],
        'curriculum'  => [
            ['title' => 'Neural Network Foundations', 'lessons' => 8],
            ['title' => 'Convolutional Neural Networks', 'lessons' => 12],
            ['title' => 'Recurrent Networks & LSTMs', 'lessons' => 10],
            ['title' => 'Attention & Transformers', 'lessons' => 14],
            ['title' => 'Generative Models', 'lessons' => 12],
            ['title' => 'Capstone Projects', 'lessons' => 8],
        ],
    ],
    [
        'id'          => 3,
        'slug'        => 'generative-ai-llms',
        'title'       => 'Generative AI & Large Language Models',
        'subtitle'    => 'Harness the power of GPT, Claude & beyond',
        'category'    => 'Generative AI',
        'level'       => 'Advanced',
        'duration'    => '10 weeks',
        'lessons'     => 40,
        'students'    => 31200,
        'rating'      => 4.9,
        'reviews'     => 4150,
        'price'       => 249,
        'old_price'   => 499,
        'instructor'  => 'Dr. Maya Patel',
        'instructor_title' => 'LLM Researcher, OpenAI',
        'color'       => '#10b981',
        'icon'        => 'sparkles',
        'badge'       => 'Hot',
        'tags'        => ['Prompt Eng.', 'Fine-tuning', 'RAG', 'LangChain'],
        'description' => 'Master the most transformative technology of our era. Learn to fine-tune LLMs, build RAG pipelines, and create production-grade AI applications with the latest models.',
        'outcomes'    => [
            'Master advanced prompt engineering techniques',
            'Fine-tune LLMs on custom datasets',
            'Build RAG systems with vector databases',
            'Create AI agents with tool use capabilities',
        ],
        'curriculum'  => [
            ['title' => 'LLM Architecture Deep Dive', 'lessons' => 6],
            ['title' => 'Prompt Engineering Mastery', 'lessons' => 8],
            ['title' => 'Fine-tuning Techniques', 'lessons' => 8],
            ['title' => 'RAG & Vector Databases', 'lessons' => 8],
            ['title' => 'AI Agents & Orchestration', 'lessons' => 6],
            ['title' => 'Production Deployment', 'lessons' => 4],
        ],
    ],
    [
        'id'          => 4,
        'slug'        => 'computer-vision-mastery',
        'title'       => 'Computer Vision Mastery',
        'subtitle'    => 'Teach machines to see and understand the world',
        'category'    => 'Computer Vision',
        'level'       => 'Intermediate',
        'duration'    => '14 weeks',
        'lessons'     => 56,
        'students'    => 12400,
        'rating'      => 4.7,
        'reviews'     => 1820,
        'price'       => 179,
        'old_price'   => 349,
        'instructor'  => 'Dr. James Park',
        'instructor_title' => 'Computer Vision Scientist, Tesla',
        'color'       => '#f59e0b',
        'icon'        => 'eye',
        'badge'       => 'New',
        'tags'        => ['OpenCV', 'YOLO', 'Segmentation', 'Detection'],
        'description' => 'From image classification to real-time object detection, learn the complete computer vision pipeline. Build systems that power autonomous vehicles, medical imaging, and more.',
        'outcomes'    => [
            'Build image classification systems',
            'Implement object detection with YOLO',
            'Perform semantic and instance segmentation',
            'Deploy vision models on edge devices',
        ],
        'curriculum'  => [
            ['title' => 'Image Processing Fundamentals', 'lessons' => 8],
            ['title' => 'Deep Learning for Vision', 'lessons' => 10],
            ['title' => 'Object Detection', 'lessons' => 10],
            ['title' => 'Image Segmentation', 'lessons' => 10],
            ['title' => '3D Vision & Depth', 'lessons' => 10],
            ['title' => 'Edge Deployment', 'lessons' => 8],
        ],
    ],
    [
        'id'          => 5,
        'slug'        => 'nlp-natural-language-processing',
        'title'       => 'NLP: Natural Language Processing',
        'subtitle'    => 'Build AI that reads, understands & generates text',
        'category'    => 'NLP',
        'level'       => 'Intermediate',
        'duration'    => '12 weeks',
        'lessons'     => 50,
        'students'    => 15600,
        'rating'      => 4.8,
        'reviews'     => 2100,
        'price'       => 169,
        'old_price'   => 329,
        'instructor'  => 'Dr. Lena Fischer',
        'instructor_title' => 'NLP Lead, Hugging Face',
        'color'       => '#ec4899',
        'icon'        => 'chat',
        'badge'       => 'Popular',
        'tags'        => ['BERT', 'Transformers', 'spaCy', 'NLTK'],
        'description' => 'Master natural language processing from tokenization to state-of-the-art transformer models. Build chatbots, sentiment analyzers, and text generation systems.',
        'outcomes'    => [
            'Process and analyze text data at scale',
            'Fine-tune BERT and GPT models',
            'Build production NLP pipelines',
            'Create intelligent chatbots and assistants',
        ],
        'curriculum'  => [
            ['title' => 'Text Processing Basics', 'lessons' => 6],
            ['title' => 'Classical NLP Methods', 'lessons' => 8],
            ['title' => 'Word Embeddings', 'lessons' => 8],
            ['title' => 'Transformer Architecture', 'lessons' => 12],
            ['title' => 'Applied NLP Projects', 'lessons' => 10],
            ['title' => 'Deployment & Scaling', 'lessons' => 6],
        ],
    ],
    [
        'id'          => 6,
        'slug'        => 'reinforcement-learning',
        'title'       => 'Reinforcement Learning & AI Agents',
        'subtitle'    => 'Train agents that learn through interaction',
        'category'    => 'Reinforcement Learning',
        'level'       => 'Advanced',
        'duration'    => '14 weeks',
        'lessons'     => 52,
        'students'    => 8900,
        'rating'      => 4.7,
        'reviews'     => 1240,
        'price'       => 219,
        'old_price'   => 429,
        'instructor'  => 'Prof. Marcus Webb',
        'instructor_title' => 'RL Researcher, DeepMind',
        'color'       => '#ef4444',
        'icon'        => 'robot',
        'badge'       => 'Expert',
        'tags'        => ['OpenAI Gym', 'PPO', 'DQN', 'Multi-Agent'],
        'description' => 'Learn how AI systems master games, robotics, and real-world tasks through trial and error. Implement state-of-the-art RL algorithms from Q-learning to PPO.',
        'outcomes'    => [
            'Implement core RL algorithms from scratch',
            'Train agents in complex environments',
            'Apply deep RL to robotics simulations',
            'Design multi-agent systems',
        ],
        'curriculum'  => [
            ['title' => 'RL Fundamentals', 'lessons' => 8],
            ['title' => 'Value-Based Methods', 'lessons' => 10],
            ['title' => 'Policy Gradient Methods', 'lessons' => 10],
            ['title' => 'Actor-Critic Algorithms', 'lessons' => 10],
            ['title' => 'Multi-Agent RL', 'lessons' => 8],
            ['title' => 'Real-World Applications', 'lessons' => 6],
        ],
    ],
];

$testimonials = [
    [
        'name'   => 'Jordan Lee',
        'role'   => 'ML Engineer at Stripe',
        'avatar' => 'JL',
        'color'  => '#7c3aed',
        'rating' => 5,
        'text'   => 'I was a backend dev who always felt like ML was out of reach for me. The Fundamentals course changed that — slowly, then all at once. Three months after finishing, I got the call from Stripe. Still surreal.',
    ],
    [
        'name'   => 'Priya Sharma',
        'role'   => 'AI Researcher at Stanford',
        'avatar' => 'PS',
        'color'  => '#0ea5e9',
        'rating' => 5,
        'text'   => 'The Deep Learning course doesn\'t dumb things down — it respects your intelligence. The instructors are researchers, not just presenters, and you can feel the difference in every lesson.',
    ],
    [
        'name'   => 'Carlos Mendez',
        'role'   => 'Founder, AI startup',
        'avatar' => 'CM',
        'color'  => '#10b981',
        'rating' => 5,
        'text'   => 'The RAG and fine-tuning sections saved us literally months of figuring things out on our own. That knowledge became the foundation of our product. We just closed a $2M seed round — this course was part of that story.',
    ],
    [
        'name'   => 'Aiko Tanaka',
        'role'   => 'Computer Vision Lead at Sony',
        'avatar' => 'AT',
        'color'  => '#f59e0b',
        'rating' => 5,
        'text'   => 'I\'ve tried a lot of platforms. The difference here is that the projects feel like real work — not toy examples. And the community actually answers when you ask something. That matters more than I expected.',
    ],
];

$stats = [
    ['value' => '120K+', 'label' => 'Learners & counting', 'icon' => 'users'],
    ['value' => '98%',   'label' => 'Said they\'d recommend us', 'icon' => 'star'],
    ['value' => '50+',   'label' => 'Instructors (all active practitioners)', 'icon' => 'award'],
    ['value' => '300+',  'label' => 'Courses, updated regularly', 'icon' => 'book'],
];

$categories = ['All', 'Machine Learning', 'Deep Learning', 'Generative AI', 'Computer Vision', 'NLP', 'Reinforcement Learning'];
